### ISSUE TITLE
TDCSpectatorPawnMovement is missing

### ISSUE THREAD

**Issue by juaxix** [ntk4/UE4TopDownCamera#1]
I'm trying to find the TDCSpectatorPawnMovement class but i think it's missing from the project, can you upload it?
the project would not compile without it.

**Comment by ntk4** [comment]
Hi, yes, I'll check the issue this evening. 
Thanks for raising it.

**Comment by juaxix** [comment]
Thanks N

**Comment by ntk4** [comment]
Added the missing files and upgraded to the latest UE4 v4.11.1. However with this new version I'm having issues now with the MoveToLocation functionality. If you also have them let me know.

**Comment by juaxix** [comment]
Uhm, now i'm getting 600 errors xD 
I'm using UE 4.10.4 to compile.
The first error is 

> Error (active)    'explicit' is not allowed   UE4TopDownCamera    e:\UDK\Epic Games\4.10\Engine\Source\Runtime\CoreUObject\Public\UObject\UObjectIterator.h   308

**Comment by ntk4** [comment]
This must be something with the generated visual studio solution. I guess you tried to "Switch Unreal Engine Version..." and "Generate Visual Studio project files", then rebuild all?

**Comment by juaxix** [comment]
Yeah Nikos,now it works perfectly, thanks!

**Comment by PaulNevada** [comment]
I can't launch it with 4.18.3 - fix it, please!!
Thank you a lot!!
