### ISSUE TITLE
Add 4.18+ support, please

### ISSUE THREAD

**Issue by PaulNevada** [ntk4/UE4TopDownCamera#2]
Hi, maybe you'll give us it??

**Comment by ntk4** [comment]
Hi, thanks for showing interest in this project. It has been inactive for 2 years but I'll gladly take a look if it can be made compatible with 4.18+ when I'm back from my current trip, sometime during April.

**Comment by PaulNevada** [comment]
Superb!! Will be awaiting for your appearance here :)

**Comment by Streliteela** [comment]
Hi, thanks for sharing it.
I has got stuck a few days in making multi touch controls for my camera. I think your project may be very helpful for me. But could you upgrade to 4.18, please ! 
Thanks a lot :-)

**Comment by ntk4** [comment]
Thanks for your interest guys, I'll be very happy to help and upgrade the project. Currently I have no development environment cause I'm stuck with only an outdated Mac on which Xcode doesn't work. Windows VMs don't work with UE4 either, trying to find alternatives

**Comment by Streliteela** [comment]
Appreciate you! Wait for your upgrade :-)

**Comment by clvenk** [comment]
Hi, ntk4  can you upgarde your code to 4.20, Please..! even i want to implement in my project. **pinch** / **Swipe** Functionality

**Comment by roidanton** [comment]
You can support my [PullRequest](https://github.com/ntk4/UE4TopDownCamera/pull/3). Actually it was not much to do to port it. :-)

**Comment by ntk4** [comment]
Please all check the latest commit by @roidanton. My apologies for not having been able to do this in so long due to OS constraints, and thanks for your interest.
